version: '2'
services:
    cgserver-mongodb:
        container_name: cgserver-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb cgserver-mongodb-config
    cgserver-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    cgserver-mongodb-config:
        image: mongo:3.2.10
        container_name: cgserver-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
