version: '2'
services:
    cgserver-mongodb:
        container_name: cgserver-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/cgserver/mongodb/:/data/db/
